# Generated by Django 4.2.5 on 2023-09-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialReciclable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "precio_por_kilo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UbicacionReciclaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioRegistrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("correo", models.EmailField(max_length=255)),
                ("contraseña", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudRecoleccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso_kilos", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_solicitud", models.DateField()),
                ("fecha_recoleccion", models.DateField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectoTesis.materialreciclable",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectoTesis.usuarioregistrado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PuntosRecompensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_puntos", models.IntegerField()),
                ("fecha_creacion", models.DateField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectoTesis.usuarioregistrado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonacionMaterialReciclable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso_kilos", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_donacion", models.DateField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectoTesis.materialreciclable",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectoTesis.usuarioregistrado",
                    ),
                ),
            ],
        ),
    ]
