# Generated by Django 4.2.5 on 2023-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0004_ubicacionusuario_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialreciclable",
            name="foto",
            field=models.TextField(blank=True, null=True),
        ),
    ]
