# Generated by Django 4.2.5 on 2023-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0005_materialreciclable_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacionreciclaje",
            name="latitud",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ubicacionreciclaje",
            name="longitud",
            field=models.CharField(max_length=255),
        ),
    ]
