# Generated by Django 4.2.5 on 2023-10-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0006_alter_ubicacionreciclaje_latitud_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialreciclable",
            name="precio_por_kilo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
