# Generated by Django 4.2.5 on 2023-10-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0007_alter_materialreciclable_precio_por_kilo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudrecoleccion",
            name="peso_kilos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
