# Generated by Django 4.2.5 on 2023-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0008_alter_solicitudrecoleccion_peso_kilos"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudrecoleccion",
            name="estado",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitudrecoleccion",
            name="peso_kilos",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
