# Generated by Django 4.2.5 on 2023-10-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0009_solicitudrecoleccion_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialreciclable",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
