# Generated by Django 4.2.5 on 2023-10-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0010_materialreciclable_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudrecoleccion",
            name="reciclador",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
