# Generated by Django 4.2.5 on 2023-10-24 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0012_alter_donacionmaterialreciclable_peso_kilos_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donacionmaterialreciclable",
            old_name="peso_kilos",
            new_name="puntos",
        ),
    ]
