# Generated by Django 4.2.5 on 2023-10-24 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0013_rename_peso_kilos_donacionmaterialreciclable_puntos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donacionmaterialreciclable",
            name="material",
        ),
    ]
