# Generated by Django 4.2.5 on 2023-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0014_remove_donacionmaterialreciclable_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="quejassugerencias",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
    ]
