# Generated by Django 4.2.5 on 2023-10-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0015_quejassugerencias_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudrecoleccion",
            name="fecha_solicitud_aceptada",
            field=models.DateField(blank=True, null=True),
        ),
    ]
