# Generated by Django 4.2.5 on 2023-10-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0016_solicitudrecoleccion_fecha_solicitud_aceptada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloqueados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correos_baneados",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
