# Generated by Django 4.2.5 on 2023-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectoTesis", "0017_bloqueados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialreciclable",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
