"""
Django settings for proyectoTesis project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2#(#-q1j@w*!xxr!$ojea3$2ryo)tgk!&(ju9#(i%=j5s#j#dc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "proyectoTesis",
    'import_export',
    'django_cron',
    
    
]

CRON_CLASSES = [
    
    'proyectoTesis.cron.MiTareaDiaria',
    # ...
]

DJANGO_CRON_JOBS = [
    ('proyectoTesis.cron.MiTareaDiaria', '10 0 * * *'),  # Ejecutar MiTareaDiaria a las 00:10 UTC
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = "proyectoTesis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "proyectoTesis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bvnjv1yhlxuyr9zbfcfw',
        'USER': 'uu9g1jaddssutprp',
        'PASSWORD': 'iSCyQgCuJ0UAQ8mQ6EBr',
        'HOST': 'bvnjv1yhlxuyr9zbfcfw-mysql.services.clever-cloud.com', 
        'PORT': '3306',       
    },
    'test': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost', 
        'PORT': '3306',       
    }
}
TEST_DATABASE_ALIAS = 'test'




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es-LA"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'  # Servidor SMTP de Outlook (Hotmail)
EMAIL_PORT = 587  # Puerto de SMTP para Outlook
EMAIL_USE_TLS = True  # Usar TLS (Transport Layer Security) para la conexión segura
EMAIL_HOST_USER = 'brandon-diaz@upc.edu.co'
EMAIL_HOST_PASSWORD = 'Bsdmy23134YM'

#para configurar los archivos estaticos
STATIC_URL = "/proyectoTesis/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'proyectoTesis', 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'proyectoTesis/static')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#para el inicio se sesion
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend de autenticación por defecto
]

LOGIN_URL = 'login'  # Nombre de la vista de inicio de sesión
LOGOUT_REDIRECT_URL = 'inicio' 

JAZZMIN_SETTINGS = {
    #configuramos la rita para personalizar los estilos
    "custom_css": "/css/style.css",
    "site_title": "Administrador",

    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # aqui se pueden poner links en el navbar
        # {"model": "auth.User"},
        # {"model": "proyecto.Estudiante"},
        # {"model": "proyecto.Materia"},
        # {"model": "proyecto.EstudianteMateria"},

        
    ],

    "usermenu_links": [
        {"name": "Volver a la página", "url": "/", "icon": "fas fa-home"},
        {"name": "Olvide mi contraseña", "url": "/olvide_contrasena/", "icon": "fas fa-key"},
        {"name": "Verificar Solicitudes", "url": "/verificar_solicitudes/", "icon": "fas fa-key"},
    ],
    
    
    
    
}